# Guide: https://nodejs.org/en/docs/guides/nodejs-docker-webapp/
FROM node:8.9.1

# Create app directory
WORKDIR /var/www/site

# Install app dependencies
#RUN cd /var/www/site && npm install

# If you are building your code for production
# RUN npm install --only=production

EXPOSE 8080

# CMD [ "npm", "start" ]
